// <auto-generated />
using EuroFizzBuzz.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EuroFizzBuzz.Migrations
{
    [DbContext(typeof(EuroFizzBuzzContext))]
    partial class EuroFizzBuzzContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EuroFizzBuzz.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EndNumber");

                    b.Property<int>("StartNumber");

                    b.Property<int>("Timestamp");

                    b.HasKey("SubmissionId");

                    b.ToTable("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
